### ISSUE TITLE
Problems with zoneminder adapter after upgrading iobroker to js.controller 3.1.4

### ISSUE THREAD

**Issue by maxgrosse1** [iobroker-community-adapters/ioBroker.zoneminder#8]
After upgrading to js.controller 3.1.4 the zoneminder adapter is not working any more and throws following log lines (cf. picture). Would you be so kind to advise. Thx.

![log_file](https://user-images.githubusercontent.com/65607215/82332807-26297380-99e6-11ea-9024-708a34d19b41.JPG)

**Comment by Reeeves** [comment]
I'm getting the same error log.

Zoneminder: v1.34.15
js controller:  3.1.4
Node.js: v10.20.1
NPM: 6.14.4

Thank you for any assistance!

**Comment by alpenhase83** [comment]
I'm getting the same error log, too.

Zoneminder: v1.34.20
js controller: 4.7.4
Node.js: v12.18.3
NPM: 6.14.4

Can somebody assist, please?

**Comment by falkoz** [comment]
I had the same error. It just appears if you have an error in your config (mine was a wrong port in the URL to the zoneminder server). Double check your settings. If you still cannot get the problem, go to /opt/iobroker/node_modules/iobroker.zoneminder/lib (repective your install path for iobroker) edit api.js with a editor of your choice. Got line 224 (you can search for "Cookies" ;) ), terminiate the line with a semicolon and comment the following .catch phrase up to the line "});" with "//" (6 lines at all). The adapter will still die, but it will tell you now the problem in the log instead of the bogus JSON error.

**Comment by mcm1957** [comment]
Issues seems to be outdated.
If there is still a issue with current releases please open a new issue.
